version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: mimemagic
    versions:
    - 0.3.10
    - 0.3.6
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: nio4r
    versions:
    - 2.5.7
  - dependency-name: msgpack
    versions:
    - 1.4.2
  - dependency-name: minitest
    versions:
    - 5.14.3
    - 5.14.4
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
  - dependency-name: i18n
    versions:
    - 1.8.7
    - 1.8.8
  - dependency-name: webdrivers
    versions:
    - 4.5.0
